name: DISCORD_WEBHOOK

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Kirim notifikasi ke Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"@everyone bot update silahkan execute ulang ditermux jika ingin mencoba🚀🚀\", \"allowed_mentions\": {\"parse\": [\"everyone\"]}}" \
          "${{ secrets.DISCORD_WEBHOOK }}"
